$(".carouselBackground").slick({
  slidesToShow: 1,
  slidesToScroll: 1,
  arrows: false,
  // fade: true,
  asNavFor: ".carouselInfo",
  speed: 1500,
  pauseOnFocus: false,
  pauseOnHover: false,
  // autoplay: true,
  // autoplaySpeed: 5000,
  Infinite: true,
});
// $(".carouselImagenes").slick({
//   slidesToShow: 1,
//   slidesToScroll: 1,
//   arrows: false,
//   // fade: true,
//   asNavFor: ".carouselInfo",
//   speed: 1900,
//   pauseOnFocus: false,
//   pauseOnHover: false,
//   // autoplay: true,
//   // autoplaySpeed: 5000,
//   Infinite: true,
// });
$(".carouselInfo").slick({
  slidesToShow: 1,
  slidesToScroll: 1,
  asNavFor: ".carouselBackground",
  arrows: true,
  dots: false,
  // fade: true,
  cssEase: "ease",
  // centerMode: true,
  focusOnSelect: false,
  speed: 2500,
  pauseOnFocus: false,
  pauseOnHover: false,
  // autoplay: true,
  // autoplaySpeed: 5000,
  Infinite: true,
  prevArrow: $(".next"),
  nextArrow: $(".prev"),
  responsive: [
    {
      breakpoint: 991,
      settings: {
        fade: true,
      },
    },
  ],
});
